### ISSUE TITLE
Thanks for your project,but the result seems not expected

### ISSUE THREAD

**Issue by yuanboliu** [chettiargautam/Attention-for-Translation#3]

**Comment by yuanboliu** [comment]
**SOURCE**: There were also, indeed, several thick watch-coats of the seamen’s which were left, but they were too hot to wear; and though it is true that the weather was so violently hot that there was no need of clothes, yet I could not go quite naked—no, though I had been inclined to it, which I was not—nor could I abide the thought of it, though I was alone.
    **TARGET**: Ereditai veramente ancora parecchie casacche di marinai, ma queste erano troppo pesanti a portarsi. E qui notate che se bene il caldo del clima sia si violento che non v’è bisogno di panni d’alcuna sorta, pure non potei andar nudo del tutto quand’anche tal fosse stata la mia inclinazione, che non era, perchè non ho mai saputo adattarmi nemmeno all’idea di ciò, benchè fossi affatto solo.
 **PREDICTED**: riebbi riebbi riebbi riebbi riebbi commovente riebbi riebbi riebbi riebbi diventare diventare diventare diventare diventare riebbi riebbi riebbi riebbi riebbi riebbi riebbi diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare riebbi riebbi riebbi diventare diventare diventare diventare diventare riebbi riebbi riebbi diventare diventare riebbi riscaldava riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare riebbi riebbi riebbi riebbi diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi commovente riebbi riebbi riebbi diventare diventare diventare riebbi riebbi riebbi riebbi riebbi diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare riebbi riebbi riebbi riebbi diventare diventare diventare diventare diventare diventare riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi diventare diventare diventare riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi diventare diventare diventare riebbi convinsi riebbi diventare diventare diventare diventare diventare riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi riebbi diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare piselli piselli piselli piselli piselli piselli diventare diventare diventare diventare cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono riebbi cominciarono cominciarono cominciarono cominciarono cominciarono diventare diventare diventare diventare cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono cominciarono diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare diventare

**Comment by chettiargautam** [comment]
You are right, the code isnt completed yet and theres a lot of finetuning yet to be done, once its done ill notify and resolve this.

**Comment by yuanboliu** [comment]
Thanks for your reply, good job. It's good for beginner

**Comment by chettiargautam** [comment]
Before closing this issue and the repository itself, a few pointers.

After maxing out the training on a bs of 32 and around 100 epochs, the results do get just slightly better, but there is no more convergence beyond that point, and after reading a few articles, the model needs to be pre-trained on a really huge generalizable dataset first before fine-tuning it for this task. Which means that it won't be doable directly, but something slightly better than your output is the best training from scratch on 32k data points can achieve.

Best,
G
